name = "edgetunnel-vless"
main = "worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
#UUID = ""
WS_PATH = "/vless"
PROXY_URL = "https://galaxytunnel.github.io/PROXYIP.txt"
PROXY_IP = "cdn.xn--b6gac.eu.org"
